### ISSUE TITLE
Connect API -> Blazor

### ISSUE THREAD

**Issue by KurnakovMaksim** [KurnakovMaksim/NotSocialNetwork_Blazor#14]

**Comment by Ulyanov-programmer** [comment]
The API cannot be used due to an error indicating a project incompatibility: 
_“The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps. Remove the platform link if there is a direct link to it, or the link for the package that adds the platform. communication."_

I will try to change the API project type from a console application to a **library application**, maybe this will help.

**Comment by Ulyanov-programmer** [comment]
I tried to work with the API but it always returned html markup (this is the markup of the main page), 2 hours of searching the net yielded nothing.
Below is the code that clearly demonstrates the fact of html return.
I like the idea of web api less and less, it seems to be worth abandoning it in favor of the possibility of direct access to controllers.
```javascript 
protected override async Task OnInitializedAsync()
    {
        var httpGet = Http.GetAsync("https://localhost:44374/api/UserController").Result;
        if (httpGet.IsSuccessStatusCode)
        {
            var v = httpGet.Content.ReadAsStringAsync().Result;
            // Content is text/html, it cannot be converted to json.
        }
        else
        {

        }
    }
    ```

**Comment by KurnakovMaksim** [comment]
You are wrong, the controller is returning a json file. This problem comes from because you using blazor. I use js script and everything works.

**Comment by Ulyanov-programmer** [comment]
It turned out that the API needs to be launched together with the UI, then everything will work.
_(below is when I found out the api is working)_
![image](https://user-images.githubusercontent.com/66691708/112281214-40378080-8c9f-11eb-87d2-3573376f432d.png)
